config/routes.rb
Raffler::Application.routes.draw do

  scope "api" do
    resources :entries
    resources :companies
    resources :fundings
  end

  root to: "main#index"
  match '*path', to: 'main#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :fundings

  def as_json(options={})
    {:id  => self.id,
     :name => self.name,
      :location => self.location,
      :portfolio => self.portfolio,
      :fundings => self.fundings}
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :name
  validates_length_of :name, :maximum=>20, :message=>"cannot be longer than 20 characters"
end

app/models/funding.rb
class Funding < ActiveRecord::Base
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  respond_to :json

  def index
    respond_with Company.all
  end

  def show
    respond_with Company.find(params[:id])
  end

  def create
    respond_with Company.create(params[:entry])
  end

  def update
    respond_with Company.update(params[:id], params[:entry])
  end

  def destroy
    respond_with Company.destroy
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  respond_to :json

  def index
    respond_with Entry.all
  end

  def show
    respond_with Entry.find(params[:id])
  end

  def create
    respond_with Entry.create(params[:entry])
  end

  def update
    respond_with Entry.update(params[:id], params[:entry])
  end

  def destroy
    respond_with Entry.destroy
  end
end

app/controllers/fundings_controller.rb
class FundingsController < ApplicationController
  respond_to :json

  def index
    respond_with Funding.all
  end

  def show
    respond_with Funding.find(params[:id])
  end

  def create
    respond_with Funding.create(params[:entry])
  end

  def update
    respond_with Funding.update(params[:id], params[:entry])
  end

  def destroy
    respond_with Funding.destroy
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :portfolio %><br />
    <%= f.text_field :portfolio %>
  </div>
    <div class="field">
        <%= f.label :location %><br />
        <%= f.text_field :location %>
      </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div id="container">Loading...</div>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Portfolio:</b>
  <%= @company.portfolio %>
</p>

<p>
  <b>Portfolio:</b>
  <%= @company.location %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raffler</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script src="http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
  <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCUNp-Z6XFulwmPEMP3_GOZr5UB3j6j8Sc&sensor=false" type="text/javascript"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<%= content_tag "div", "Please check you have the correct Url", id: "container", data: { entries: Entry.all, companies: Company.all, fundings: Funding.all} %>